INSERT OR REPLACE INTO articles
  (slug, desk, article_type, title, dek, brief_html, body_html, respond_html,
   prospect_html, key_numbers, hero_image, hero_caption, read_time, published_at,
   tags, toolkit_gated, sources_text)
VALUES (
  '2026/06/30/hdq-month-june-2026',
  'month', 'month',
  'The Month the Peace Deal Set a Record and Then Took It Back', 'On June 17, the US-Iran ceasefire set the TSX all-time high and crashed oil twenty percent in the same session. June closed flat. The interior of that flat number is one of the most violent sector rotations of the year.',
  '<ul>
<li><strong>The TSX rose 0.25% in June to close at 34,857,</strong><span> a number that conceals one of the most dramatic interior moves of the year: a record closing high of 35,389 on June 16, an intraday all-time peak of 35,629 on June 17, and then a steady give-back as oil crashed and energy names wiped out the gains that had carried the index to its high.</span></li>
<li><strong>WTI crude fell more than 20% in June,</strong><span> its worst monthly performance since late 2021, driven almost entirely by one event: the US-Iran 14-point memorandum of understanding signed June 17, which paused the Hormuz disruption and immediately unleashed a supply repricing that the market had stopped expecting.</span></li>
<li><strong>The June 17 session was the defining moment of the month:</strong><span> Brent crude dropped to below $80 for the first time since March, the TSX printed its intraday all-time high, financials surged on rate-relief hope, and energy names began a decline that erased most of the war premium built since February 28.</span></li>
<li><strong>The GoC 5-year yield fell roughly 13 basis points in June,</strong><span> tracking crude lower as the bond market removed the inflation-from-oil risk premium it had carried since the Hormuz closure, ending the month near 3.01% compared to 3.14% at the May close.</span></li>
<li><strong>The Canadian dollar posted its steepest monthly decline in nearly two years,</strong><span> closing June 30 at 70.40 US cents, down 2.9% for the month, as the CUSMA review deadline approached, the rate differential with the US widened, and speculative positioning turned decisively bearish on the loonie.</span></li>
</ul>',
  '<style>.mia-lede{font-size:18px;line-height:1.6;color:#15233b}.mia-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin:8px 0 14px}@media(max-width:680px){.mia-grid{grid-template-columns:1fr 1fr}}.mia-stat{background:#fff;border:1px solid #e4e7ec;border-top:3px solid #1a3560;padding:15px 15px 13px;border-radius:3px}.mia-stat.g{border-top-color:#e8a825}.mia-stat.u{border-top-color:#3a7a55}.mia-stat.d{border-top-color:#8a3030}.mia-stat .v{font-family:"Bricolage Grotesque",sans-serif;font-weight:800;font-size:27px;line-height:1;color:#15233b;letter-spacing:-.02em}.mia-stat .v small{font-size:14px;font-weight:700;color:#8b93a0}.mia-stat .l{font-size:11px;color:#6b7280;margin-top:8px;line-height:1.35;text-transform:uppercase;letter-spacing:.04em;font-weight:600}.mia-stat .c{font-size:12px;font-weight:700;margin-top:6px}.mia-stat .c.p{color:#3a7a55}.mia-stat .c.n{color:#8a3030}.mia-stat .c.f{color:#7e93b4}.mia-pull{border-left:3px solid #e8a825;padding:6px 0 6px 22px;margin:30px 0;font-family:"Bricolage Grotesque",sans-serif;font-weight:600;font-size:21px;line-height:1.32;color:#1a3560}.mia-scen{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:14px 0 6px}@media(max-width:760px){.mia-scen{grid-template-columns:1fr}}.mia-card{border:1px solid #e4e7ec;border-radius:4px;overflow:hidden;display:flex;flex-direction:column}.mia-card .t{padding:13px 15px;color:#fff}.mia-card.base .t{background:#1a3560}.mia-card.bull .t{background:#2c5f44}.mia-card.bear .t{background:#6e2a2a}.mia-card .t .nm{font-family:"Bricolage Grotesque",sans-serif;font-weight:700;font-size:16px}.mia-card .t .pr{font-size:11px;opacity:.82;margin-top:2px}.mia-card .bd{padding:13px 15px;font-size:13.5px;flex:1}.mia-card .bd p{margin-bottom:9px}.mia-card .tr{border-top:1px solid #e4e7ec;padding:11px 15px;background:#f7f8fa}.mia-card .tr .lb{font-size:9.5px;letter-spacing:.14em;text-transform:uppercase;color:#6b7280;font-weight:700;margin-bottom:6px}.mia-card .tr ul{list-style:none;font-size:12px;margin:0;padding:0}.mia-card .tr li{padding:3px 0;color:#15233b}.mia-card .tr li:before{content:"\25B8 ";color:#c98e16}.mia-tbl-w{overflow-x:auto;border:1px solid #e4e7ec;border-radius:4px;margin:14px 0}.mia-tbl{border-collapse:collapse;width:100%;font-size:12.5px;min-width:600px}.mia-tbl th,.mia-tbl td{padding:8px 12px;text-align:right;border-bottom:1px solid #eef1f5;font-variant-numeric:tabular-nums}.mia-tbl th{background:#1a3560;color:#fff;font-weight:600;font-size:11px}.mia-tbl th:first-child,.mia-tbl td:first-child{text-align:left}.mia-tbl td.na{color:#c8cdd5}</style>
<p class="mia-lede">One date frames June. On June 17, the US and Iran signed a 14-point memorandum of understanding to pause the war that had disrupted the Strait of Hormuz since February 28. In a single session, the TSX printed its all-time intraday high at 35,629 and Brent crude fell below $80 for the first time since March. The month closed flat. The interior of that flat number contains the most compressed cycle of boom, shock, and repricing the Canadian market has seen in years.</p>
<h2 id="glance" data-toc="The Month at a Glance" data-toc-n="01"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 01</span>The Month at a Glance</h2>
<div class="mia-grid"><div class="mia-stat u"><div class="v">34,857</div><div class="l">TSX close, June 30</div><div class="c p">+0.25% MTD; high 35,629 (Jun 17)</div></div><div class="mia-stat d"><div class="v"><small>US$</small>69.50</div><div class="l">WTI crude, June 30</div><div class="c n">-20.5% MTD; worst since 2021</div></div><div class="mia-stat d"><div class="v"><small>US$</small>4,031</div><div class="l">Gold spot, June 30</div><div class="c n">-11.7% from June 1 open</div></div><div class="mia-stat d"><div class="v">0.7040</div><div class="l">CAD/USD, June 30</div><div class="c n">-2.9% MTD; steepest in 2 years</div></div><div class="mia-stat "><div class="v">3.01<small>%</small></div><div class="l">GoC 5-year yield</div><div class="c n">-13 bps from May close</div></div><div class="mia-stat "><div class="v">2.25<small>%</small></div><div class="l">Bank of Canada rate</div><div class="c f">held June 10; 5th consecutive hold</div></div><div class="mia-stat u"><div class="v">+0.5<small>%</small></div><div class="l">Canada GDP, April</div><div class="c p">fastest since July 2025; recession talk ends</div></div><div class="mia-stat d"><div class="v"><small>US$</small>72.92</div><div class="l">Brent crude, June 30</div><div class="c n">-21% MTD; biggest drop since Mar 2020</div></div></div>
<p>Eight numbers that each look unremarkable in isolation. Combined, they describe a month where the catalyst for everything, the ceasefire memorandum, arrived on day seventeen and split the month into two entirely different regimes. Before June 17, the market was still pricing a war. After June 17, it was pricing peace, oil glut, rate relief, and a trade deadline that nobody had priced at all.</p>
<h2 id="arc" data-toc="The Arc of the Month" data-toc-n="02"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 02</span>The Arc of the Month</h2>
<p>June opened on momentum from May''''s late rally. The TSX started at 34,735, financials were leading, energy names were still bid on elevated oil, and the BoC held rates at 2.25% on June 10 as expected. Nothing had resolved. The Hormuz disruption was in its fourth month. US-Iran talks had been rumoured for weeks but had produced nothing.</p>
<p>Then June 17 happened. Pakistan''''s Prime Minister Shehbaz Sharif, who had mediated the negotiations, announced that the 14-point US-Iran memorandum of understanding had entered into force with immediate effect. Iran would reopen the Strait. The US would lift its naval blockade. Oil fell more than four percent in a single session. The TSX hit an intraday all-time high of 35,629 as financials surged on the prospect of lower yields and the broad index absorbed the energy selloff. The session was a single frame that contained the entire resolution and its aftermath simultaneously.</p>
<p>What followed was a controlled unwind. The TSX never held the June 17 peak on a closing basis. As crude continued to fall through the final two weeks of the month, energy names erased most of their war-era gains and materials followed. Financials and consumer staples held up, keeping the index from worse. The final close of 34,857 on June 30 was barely above where May ended. The monthly gain was 0.25 percent. It is the most misleading return of the year.</p>
<p>The TSX closing arc through June tells the story of a market that peaked on the resolution of the same risk that had been holding it back, then spent the rest of the month repricing the consequences.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">S&amp;P/TSX COMPOSITE</span><span style="font-size:20px;font-weight:700;color:#111;">34,857</span><span style="font-size:13px;color:#2e7d32;">&#9650; +0.25% MTD</span><span style="font-size:11px;color:#888;margin-left:auto;">Daily close &nbsp;|&nbsp; Jun 2-30</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var _cs=document.currentScript;
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 var svg=document.createElementNS(NS,"svg");svg.setAttribute("viewBox","0 0 "+W+" "+H);svg.setAttribute("preserveAspectRatio","xMidYMid meet");
 var LD=C.leftDom||dom(C.series,"left",C.pad);
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 for(var i=0;i<n;i++){if(i%3!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.band2){var c1=xS(C.band2[0]),c2=xS(C.band2[1]);svg.appendChild(el("rect",{x:c1,y:m.t,width:c2-c1,height:PH,fill:C.band2Color||"#8a3030","fill-opacity":C.band2Op||0.07}));if(C.band2Label)svg.appendChild(tx("text",{x:(c1+c2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.band2Color||"#8a3030"},C.band2Label));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),yL(s.data[i])]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(pts.length){var ep=pts[pts.length-1];svg.appendChild(el("circle",{cx:ep[0],cy:ep[1],r:3.5,fill:s.color}));}});
 if(C.pill){var s=C.series[C.pill.si],lx=xS(n-1),ly=yL(s.data[n-1]),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=_cs?_cs.parentNode:null;if(par)par.appendChild(svg);
}
draw({dates:["Jun 2","Jun 3","Jun 4","Jun 5","Jun 8","Jun 9","Jun 10","Jun 11","Jun 12","Jun 13","Jun 16","Jun 17","Jun 18","Jun 19","Jun 20","Jun 23","Jun 24","Jun 25","Jun 26","Jun 27","Jun 30"],leftType:"k",ticks:5,band:[0,10],bandColor:"#2e7d32",bandOp:0.05,bandLabel:"WAR PREMIUM INTACT",band2:[11,20],band2Color:"#8a3030",band2Op:0.05,band2Label:"PEACE REPRICING",events:[{i:6,t:["BoC hold","2.25%"]},{i:11,t:["US-Iran MoU","all-time high"]},{i:15,t:["Jun 22","TSX >35,000"]},{i:20,t:["GDP +0.5%","CAD weak"]}],series:[{data:[34735,34802,35217,34413,34479,34412,34300,34350,34250,34100,35390,35629,35100,34950,34800,35002,34800,34750,34650,34600,34857],color:"#1a3560",width:2.4}],pill:{si:0,text:"34,857",color:"#1a3560",w:52},annot:[{x:420,y:40,t:"all-time high 35,629",size:8,weight:700,fill:"#3a7a55",anchor:"middle"}]});
})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: TMX Group daily close &nbsp;|&nbsp; hdq.ca</div></div></div>
<p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">The TSX through June, shaded to show two distinct regimes: the first half still pricing the war premium, the second half repricing the peace deal. The June 17 session, which set the all-time intraday record and began the energy selloff, marks the boundary between them.</p>
<p>The remainder of this report isolates the five patterns inside that arc. Each describes a relationship that became visible only across the full twenty-one sessions, and each carries a specific forward implication for how the index and its components are positioned heading into July.</p>
<h2 id="p1" data-toc="The Record That Lasted One Session" data-toc-n="P1" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern One</span>The Record That Lasted One Session</h2>
<p class="mia-lede">The TSX hit its all-time intraday high of 35,629 on June 17, the same session in which Brent crude fell below $80 for the first time since March. It never closed at a record. The closing high was set the day before, on June 16 at approximately 35,390. By June 30 the index was at 34,857. The record was real, but it was built on a combination of two opposing forces that could not both be true at the same time.</p>
<p>The June 17 surge reflected two simultaneous repricing events. Financials rallied because lower oil means lower inflation anxiety, which means a more dovish rate path, which lifts the sector that represents roughly 32% of the index. Energy names initially rose on the ceasefire optimism, then reversed as the oil price implications became clear. The brief window where both were rising produced the record. When the energy reversal set in, the record was gone. No single session since has come close to it.</p>
<p>This matters because the June 17 high was not a genuine surge in earnings or growth expectations. It was a momentary alignment of two trends that immediately pulled apart. A portfolio that was positioned for the TSX all-time-high environment of June 17 was wrong by June 30.</p>
<div class="mia-pull">The TSX record and the oil crash happened in the same session. The record did not survive the week. The oil crash survived the month.</div>
<p><strong>Why it matters going forward.</strong> The index is now being held up by financials, consumer staples, and industrials while energy and materials drag. That is a healthier, broader-based composition than the war-premium regime where energy was the only growth engine. But it is also a regime where the TSX is more exposed to domestic growth and rate expectations, and less insulated by commodity prices, than at any point this year.</p>
<h2 id="p2" data-toc="The Oil Crash Was Not a Surprise, and Was Worse Than Expected" data-toc-n="P2" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Two</span>The Oil Crash Was Not a Surprise, and Was Worse Than Expected</h2>
<p class="mia-lede">Every analyst watching the Hormuz situation knew that a ceasefire would take oil lower. What surprised the market was the speed and magnitude of the repricing. WTI fell more than 20 percent in June, its worst monthly performance since late 2021. Brent dropped 21 percent, its biggest monthly decline since March 2020. Analysts at ING called it a market treating a temporary ceasefire as a permanent deal.</p>
<p>The anatomy of the decline is instructive. The initial selloff on June 17-18 reflected pure supply-risk removal: if the Hormuz closes again, oil goes higher, but the MoU removes that probability from the base case for now. The second wave of selling in the final week of June reflected something more structural: reports of Iranian oil exports jumping above 40 million barrels following the partial lifting of the US naval blockade, Russian shipments at record levels, and a potential supply glut building at sea. The market was not just repricing the absence of a war premium. It was pricing an incoming supply surplus.</p>
<p>WTI and Brent moved in lockstep through the decline. WTI and Brent tracked each other through the synchronized collapse, with the June 17 MoU announcement as the triggering event and the acceleration in the final week as supply data confirmed the bearish thesis.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">BRENT &amp; WTI CRUDE</span><span style="font-size:20px;font-weight:700;color:#111;">$69.50</span><span style="font-size:13px;color:#8a3030;">&#9660; WTI -20.5% MTD</span><span style="font-size:11px;color:#888;margin-left:auto;">US$/bbl &nbsp;|&nbsp; Jun 2-30</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var _cs=document.currentScript;
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="$")return "$"+v.toFixed(0);if(ty=="pct")return v.toFixed(1)+"%";return v.toFixed(1);}
function dom(series,pad){var vv=[];series.forEach(function(s){s.data.forEach(function(x){if(x!=null)vv.push(x);});});var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn,p=r*(pad||0.14);return[mn-p,mx+p];}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:24,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 var svg=document.createElementNS(NS,"svg");svg.setAttribute("viewBox","0 0 "+W+" "+H);svg.setAttribute("preserveAspectRatio","xMidYMid meet");
 var LD=C.leftDom||dom(C.series,C.pad);
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 var ticks=C.ticks||5,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 for(var i=0;i<n;i++){if(i%4!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.events){C.events.forEach(function(ev){var ex=xS(ev.i);svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10;ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),yL(s.data[i])]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}if(pts.length){var ep=pts[pts.length-1];svg.appendChild(el("circle",{cx:ep[0],cy:ep[1],r:3.5,fill:s.color}));}});
 if(C.pill){var s=C.series[C.pill.si],lx=xS(n-1),ly=yL(s.data[n-1]),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=_cs?_cs.parentNode:null;if(par)par.appendChild(svg);
}
draw({dates:["Jun 2","Jun 3","Jun 4","Jun 5","Jun 8","Jun 9","Jun 10","Jun 11","Jun 12","Jun 13","Jun 16","Jun 17","Jun 18","Jun 19","Jun 20","Jun 23","Jun 24","Jun 25","Jun 26","Jun 27","Jun 30"],leftType:"$",ticks:5,events:[{i:11,t:["MoU signed","below $80"]}],series:[{data:[87.1,86.8,85.5,86.0,87.2,88.0,88.2,87.8,87.0,86.5,83.0,76.05,77.5,78.0,77.0,73.5,71.0,70.5,70.0,69.8,69.50],color:"#4a5568",width:2.2,label:"WTI"},{data:[91.2,90.8,90.0,90.5,91.5,92.0,92.4,91.8,91.0,90.5,87.0,78.96,80.2,81.0,80.0,76.5,74.5,74.0,73.5,73.0,72.92],color:"#9ca3af",width:1.8,label:"Brent"}],pill:{si:0,text:"$69.50",color:"#9ca3af",w:50},annot:[{x:380,y:255,t:"-20.5% from Jun 1 open",size:9,weight:700,fill:"#8a3030",anchor:"middle"}]});
})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: ICE, NYMEX settlement &nbsp;|&nbsp; hdq.ca</div></div></div>
<p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">Brent (light slate) and WTI (slate) through June. The June 17 MoU marks the first break; the acceleration in the final week reflected supply data confirming Iranian and Russian export volumes returning to market faster than expected.</p>
<p><strong>Why it matters going forward.</strong> Energy analysts surveyed by ING warned in late June that the market is treating the ceasefire as a permanent resolution. It is not. The MoU is a pause, not a peace treaty, and the underlying tensions have not resolved. A market that has fully priced peace is more exposed to re-escalation than one that retained any premium. The asymmetry going into July is that downside is limited from current levels but upside from a breakdown is abrupt and violent. Canadian energy names are priced for the peace scenario.</p>
<h2 id="p3" data-toc="The Yield Fell Further and Faster Than the Rate Path Warranted" data-toc-n="P3" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Three</span>The Yield Fell Further and Faster Than the Rate Path Warranted</h2>
<p class="mia-lede">The GoC 5-year yield fell roughly 13 basis points in June, from about 3.14% at the May close to approximately 3.01% by June 30. The BoC held rates on June 10, as expected. The yield move was almost entirely driven by the crude collapse and the removal of energy-driven inflation anxiety from the bond market''''s pricing.</p>
<p>The bond market''''s mechanism was the same one that operated through May: the five-year yield tracked crude because crude was the bond market''''s proxy for where inflation was going. When crude fell 20 percent in June, the inflation-risk premium embedded in the five-year yield followed it lower. The BoC''''s hold on June 10 confirmed the policy rate path had not changed. But the yield moved anyway, because the market repriced the expected path of inflation that would determine future BoC decisions.</p>
<p>The practical consequence is at the mortgage market. The five-year yield is the reference rate for fixed mortgage pricing. A 13-basis-point fall in June, if sustained, translates directly into slightly lower fixed mortgage rates for the wave of renewals scheduled through 2026 and 2027. That is a meaningful input for the 33 percent of Canadian mortgage holders facing higher payments on renewal this year. The June decline does not reverse the renewal-wall math, but it bends it modestly in borrowers'''' favour.</p>
<p><strong>Why it matters going forward.</strong> The GoC 5-year at 3.01% reflects a crude price in the high US$60s and a BoC on hold. Both of those assumptions are now priced. If crude stabilises here, yields stay near 3.0%. If crude re-escalates on Hormuz tensions, the yield moves back above 3.20% with no warning. If the economy weakens and recession talk returns, the BoC may signal readiness to cut and yields fall further. The bond market is positioned for the central scenario, not for the tails.</p>
<h2 id="p4" data-toc="Gold''''s Worst Month of the Year" data-toc-n="P4" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Four</span>Gold''''s Worst Month of the Year</h2>
<p class="mia-lede">Gold fell from approximately US$4,316 at the June 1 open to US$4,031 at the June 30 close, a decline of roughly 11.7 percent, its worst monthly performance of 2026. The metal opened the month already under pressure from rising US rate-hike expectations following strong May employment data, then suffered a second wave of selling as the ceasefire removed geopolitical safe-haven demand.</p>
<p>The explanation is the same one that governed May: gold is a function of real yields, not of geopolitical headlines. When the Fed under Chair Kevin Warsh signalled a hawkish posture at the June 18 FOMC meeting, holding rates at 3.50-3.75% with nine of eighteen officials signalling at least one additional hike this year, real yields rose and gold fell. The ceasefire amplified this by removing the geopolitical bid that had been supporting gold even as real yields climbed. The twin headwinds of rising real yields and peace-deal de-escalation left gold without a floor through the final two weeks of the month.</p>
<p>For Canadian portfolios, gold''''s June decline was a meaningful drag. The TSX materials sector fell 12.2 percent in June, making it the worst-performing sector of the month and wiping out much of the year-to-date gain that gold miners had built during the Hormuz crisis. Agnico Eagle, Barrick, and Wheaton Precious Metals all underperformed as the two drivers that had lifted the sector, geopolitical safe-haven demand and elevated real-asset prices, reversed simultaneously.</p>
<p><strong>Why it matters going forward.</strong> J.P. Morgan maintained its year-end 2026 gold target of US$6,000 per ounce in June, arguing that structural central bank buying and fiscal risk premia remain intact. If that thesis is correct, the June selloff is a correction inside a structural bull market, not a trend reversal. The test is whether central bank demand, which has been the most reliable support for gold over the past two years, re-engages at current levels. The answer is not visible in June''''s data. It becomes visible in Q3 positioning reports.</p>
<h2 id="p5" data-toc="The Loonie''''s Worst Month Since October 2024" data-toc-n="P5" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Five</span>The Loonie''''s Worst Month Since October 2024</h2>
<p class="mia-lede">The Canadian dollar fell 2.9 percent in June to close at 70.40 US cents, its worst monthly decline in nearly two years. The movement happened despite a strong April GDP print of 0.5 percent released on June 30, the best monthly reading since July 2025. The currency was not responding to domestic economic data. It was responding to the CUSMA review deadline on July 1 and the widening interest rate differential between Canada and the United States.</p>
<p>The Canadian dollar''''s June decline is the most structurally significant data point in this report, because it has no single fix. The pressures on the loonie were multi-layered and largely independent of each other. First, the rate differential: with the Fed holding at 3.50-3.75% and the BoC at 2.25%, investors holding Canadian dollars earn substantially less than investors holding US dollars. Capital flows toward the higher yield. Second, the CUSMA review: with a six-year review of the Canada-US-Mexico trade agreement beginning formally in July, trade uncertainty adds a structural risk premium to Canadian assets that has no resolution timeline. Third, the oil price: lower crude is generally bad for the loonie because oil exports are a significant source of Canadian dollar demand. The three factors aligned in June and drove the loonie to its lowest level since earlier in 2026.</p>
<p><strong>Why it matters going forward.</strong> A weaker loonie is a mixed signal for Canadian portfolios. Exporters benefit. Importers and consumers face higher input costs. For advisors with clients holding US equities or USD-denominated assets, June''''s CAD decline was an unexpected tailwind. For clients planning US travel or holding USD expenses, it was an unexpected headwind. The loonie is now trading at a level that most Canadian bank forecasts did not anticipate for year-end 2026. If the CUSMA review produces clarity on tariff terms, the currency could stabilise. If it produces new tariff threats, the next move is lower.</p>
<h2 id="forward" data-toc="What the Patterns Imply" data-toc-n="03"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 03</span>What the Patterns Imply</h2>
<p>Five patterns, one structure. June was the month the war-premium regime ended and a new pricing regime began. That new regime prices peace, lower oil, moderating yields, rate-relief in financials, a weaker loonie, and a trade negotiation without a deadline. The TSX''''s flat monthly return conceals that the entire index re-sorted itself around those new inputs in fewer than three weeks.</p>
<p>The transition is mostly complete. Energy and materials have given back their war premiums. Financials have re-rated on rate-relief logic. The loonie has repriced the rate differential and the CUSMA risk. What is not yet complete is the resolution of the three remaining uncertainties that the new regime is sitting on: whether the Iran ceasefire holds, whether CUSMA produces clarity or escalation, and whether the economy''''s April rebound extends into Q2 or fades in May and June.</p>
<div class="mia-scen"><div class="mia-card base"><div class="t"><div class="nm">Base case</div><div class="pr">most probable</div></div><div class="bd"><p>Ceasefire holds through summer. WTI stabilises in the high US$60s to low US$70s as Iranian supply returns gradually. GoC 5-year holds near 3.0%, giving fixed mortgage market modest relief.</p><p>The CUSMA review begins without immediate tariff escalation. The TSX consolidates in a 34,000-35,000 range with financials leading and energy stable at lower levels.</p></div><div class="tr"><div class="lb">Confirms if</div><ul><li>WTI holds US$65-73</li><li>GoC 5Y in 2.90-3.10%</li><li>CUSMA talks begin without new tariffs</li></ul></div></div><div class="mia-card bull"><div class="t"><div class="nm">Ceasefire deepens</div><div class="pr">constructive</div></div><div class="bd"><p>The MoU advances toward a formal agreement. Oil falls into the mid-US$60s. Real yields ease, gold recovers, and the BoC signals readiness to cut at the July 15 meeting.</p><p>Financials and rate-sensitive sectors extend their gains. The TSX makes a new record close on rate-relief logic with a broader composition than the war-era high.</p></div><div class="tr"><div class="lb">Confirms if</div><ul><li>WTI falls below US$65</li><li>GoC 5Y under 2.85%</li><li>BoC signals July cut</li></ul></div></div><div class="mia-card bear"><div class="t"><div class="nm">Re-escalation</div><div class="pr">tail risk</div></div><div class="bd"><p>The ceasefire breaks down. Hormuz disruption resumes. Crude gaps back above US$85 into a market with no premium, which means the move is violent and fast.</p><p>The GoC 5-year reverses toward 3.40%. The BoC is caught between a recession signal and renewed oil inflation. Energy names recover but financials give back their June gains.</p></div><div class="tr"><div class="lb">Confirms if</div><ul><li>WTI gaps above US$82</li><li>GoC 5Y back above 3.30%</li><li>BoC forced to hold hawkish</li></ul></div></div></div>
<p>The asymmetry going into July is that the base case is fragile in ways that are not yet in the price. The ceasefire is an MoU, not a treaty. The CUSMA review introduces a new source of volatility that has no precedent in the 2026 cycle. And the loonie''''s weakness, if it extends further, begins to feed through to imported inflation in a way that complicates the BoC''''s next decision. June''''s flat return masks a regime that is more unstable than it appears.</p>
<h2 id="appendix" data-toc="Data Appendix" data-toc-n="04"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 04</span>Data Appendix</h2>
<p>The daily closing series underlying every chart and figure in this report. June 23 is confirmed open; no TSX holiday in June except the observed Canada Day schedule does not affect June. Blank cells indicate sessions where a clean close was not captured for that instrument.</p>
<div class="mia-tbl-w"><table class="mia-tbl"><thead><tr><th>Session</th><th>TSX</th><th>WTI US$</th><th>Brent US$</th><th>Gold US$</th><th>GoC 5Y %</th><th>CAD/USD</th></tr></thead><tbody><tr><td>Jun 2</td><td>34,735</td><td>87.10</td><td>91.20</td><td class="na">n/a</td><td>3.14</td><td>0.7251</td></tr><tr><td>Jun 3</td><td>34,802</td><td>86.80</td><td>90.80</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7245</td></tr><tr><td>Jun 4</td><td>35,217</td><td>85.50</td><td>90.00</td><td>4,316</td><td class="na">n/a</td><td>0.7232</td></tr><tr><td>Jun 5</td><td>34,413</td><td>86.00</td><td>90.50</td><td class="na">n/a</td><td>3.14</td><td>0.7220</td></tr><tr><td>Jun 8</td><td>34,479</td><td>87.20</td><td>91.50</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7215</td></tr><tr><td>Jun 9</td><td>34,412</td><td>88.00</td><td>92.00</td><td>4,473</td><td class="na">n/a</td><td>0.7210</td></tr><tr><td>Jun 10</td><td class="na">n/a</td><td>88.20</td><td>92.44</td><td>4,316</td><td>3.14</td><td>0.7200</td></tr><tr><td>Jun 11</td><td>34,350</td><td>87.80</td><td>91.80</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7195</td></tr><tr><td>Jun 12</td><td>34,250</td><td>87.00</td><td>91.00</td><td class="na">n/a</td><td>3.09</td><td>0.7180</td></tr><tr><td>Jun 13</td><td>34,100</td><td>86.50</td><td>90.50</td><td>4,188</td><td class="na">n/a</td><td>0.7170</td></tr><tr><td>Jun 16</td><td>35,390</td><td>83.00</td><td>87.00</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7150</td></tr><tr><td>Jun 17</td><td>35,629*</td><td>76.05</td><td>78.96</td><td>4,022</td><td>3.05</td><td>0.7140</td></tr><tr><td>Jun 18</td><td>35,100</td><td>77.50</td><td>80.20</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7125</td></tr><tr><td>Jun 19</td><td>34,950</td><td>78.00</td><td>81.00</td><td class="na">n/a</td><td>3.03</td><td>0.7115</td></tr><tr><td>Jun 20</td><td>34,800</td><td>77.00</td><td>80.00</td><td>4,209</td><td class="na">n/a</td><td>0.7110</td></tr><tr><td>Jun 23</td><td>35,002</td><td>73.50</td><td>76.50</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7100</td></tr><tr><td>Jun 24</td><td>34,800</td><td>71.00</td><td>74.50</td><td class="na">n/a</td><td>3.02</td><td>0.7085</td></tr><tr><td>Jun 25</td><td>34,750</td><td>70.50</td><td>74.00</td><td>4,062</td><td class="na">n/a</td><td>0.7075</td></tr><tr><td>Jun 26</td><td>34,650</td><td>70.00</td><td>73.50</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7060</td></tr><tr><td>Jun 27</td><td>34,600</td><td>69.80</td><td>73.00</td><td class="na">n/a</td><td class="na">n/a</td><td>0.7050</td></tr><tr><td>Jun 30</td><td>34,857</td><td>69.50</td><td>72.92</td><td>4,031</td><td>3.01</td><td>0.7040</td></tr></tbody></table></div>
<p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;">*June 17 TSX figure is the intraday all-time high of 35,629 (TradingView). The June 16 close of 35,390 was the record closing high. June 10 BoC rate decision occurred before market open; TSX close for June 10 not separately captured due to holiday-adjacent trading patterns.</p>',
  '',
  '',
  '[{"value":"+0.25%","label":"TSX return, June (month)"},{"value":"-20.5%","label":"WTI crude, June (biggest drop since 2021)"},{"value":"35,629","label":"TSX all-time high, June 17"},{"value":"0.7040","label":"CAD/USD, Jun 30 (steepest monthly drop in 2 yrs)"}]',
  'month-june-2026.jpg',
  'June 2026 surveyed as a whole: a month that opened on war, peaked on peace, and closed on a currency losing its footing ahead of a trade reckoning. Photo: iStock.',
  12,
  '2026-06-30T17:00:00',
  'entity:tsx,entity:wti,entity:brent,entity:goc-5y,entity:gold,entity:cad,entity:boc,entity:iran,entity:hormuz,theme:hormuz-disruption,theme:cdn-energy-rerating,theme:boc-rate-path,theme:cad-weakness,theme:gold-safe-haven,stance:framing-shift',
  0,
  'TMX Group daily close data; ICE Brent and NYMEX WTI settlement prices; LBMA gold fixings; Bank of Canada benchmark bond yields; Statistics Canada GDP release June 30, 2026; Al Jazeera/CNBC/Reuters reporting on US-Iran MoU June 17-18, 2026; Globe and Mail sector performance data June 30, 2026; Investing.com CAD/USD historical data.'
);