INSERT OR REPLACE INTO articles
  (slug, desk, article_type, title, dek, brief_html, body_html, respond_html, prospect_html, key_numbers, hero_image, hero_caption, read_time, published_at, tags, toolkit_gated, sources_text)
VALUES (
'2026/05/29/hdq-month-may-2026',
'month', 'month',
'The Month the TSX Quietly Changed What It Was Betting On',
'Oil fell sixteen percent and a war stayed open, yet Canadian equities closed May at record highs. The months data reveals an index that quietly relocated its risk from the oil price to the rate path.',
'<ul><li><strong>The TSX rose 1.4% to a record while oil fell 16%,</strong><span> closing the month at 34,518 after an intraday all-time high of 34,575 on May 22, even as WTI crude collapsed from its May 19 peak.</span></li><li><strong>The indexs correlation to crude inverted,</strong><span> from roughly zero in early May to minus 0.87 in the second half, the signature of a market rotating out of energy and into rate-sensitive sectors.</span></li><li><strong>Gold fell 5% through an open war,</strong><span> because rising real yields, not geopolitics, governed the gold price while oil held its supply bid.</span></li><li><strong>The five-year yield tracked oil, not inflation,</strong><span> ignoring a benign 2.8% April CPI and finishing 20 basis points below its peak as crude broke down.</span></li><li><strong>Canada confirmed a technical recession on the final day,</strong><span> with Q1 GDP at minus 0.1%, reframing the rate-relief rotation as also a recession-fear rotation heading into June.</span></li></ul>',
'<style>.mia-lede{font-size:18px;line-height:1.6;color:#15233b}.mia-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin:8px 0 14px}@media(max-width:680px){.mia-grid{grid-template-columns:1fr 1fr}}.mia-stat{background:#fff;border:1px solid #e4e7ec;border-top:3px solid #1a3560;padding:15px 15px 13px;border-radius:3px}.mia-stat.g{border-top-color:#e8a825}.mia-stat.u{border-top-color:#3a7a55}.mia-stat.d{border-top-color:#8a3030}.mia-stat .v{font-family:"Bricolage Grotesque",sans-serif;font-weight:800;font-size:27px;line-height:1;color:#15233b;letter-spacing:-.02em}.mia-stat .v small{font-size:14px;font-weight:700;color:#8b93a0}.mia-stat .l{font-size:11px;color:#6b7280;margin-top:8px;line-height:1.35;text-transform:uppercase;letter-spacing:.04em;font-weight:600}.mia-stat .c{font-size:12px;font-weight:700;margin-top:6px}.mia-stat .c.p{color:#3a7a55}.mia-stat .c.n{color:#8a3030}.mia-stat .c.f{color:#7e93b4}.mia-pull{border-left:3px solid #e8a825;padding:6px 0 6px 22px;margin:30px 0;font-family:"Bricolage Grotesque",sans-serif;font-weight:600;font-size:21px;line-height:1.32;color:#1a3560}.mia-scen{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:14px 0 6px}@media(max-width:760px){.mia-scen{grid-template-columns:1fr}}.mia-card{border:1px solid #e4e7ec;border-radius:4px;overflow:hidden;display:flex;flex-direction:column}.mia-card .t{padding:13px 15px;color:#fff}.mia-card.base .t{background:#1a3560}.mia-card.bull .t{background:#2c5f44}.mia-card.bear .t{background:#6e2a2a}.mia-card .t .nm{font-family:"Bricolage Grotesque",sans-serif;font-weight:700;font-size:16px}.mia-card .t .pr{font-size:11px;opacity:.82;margin-top:2px}.mia-card .bd{padding:13px 15px;font-size:13.5px;flex:1}.mia-card .bd p{margin-bottom:9px}.mia-card .tr{border-top:1px solid #e4e7ec;padding:11px 15px;background:#f7f8fa}.mia-card .tr .lb{font-size:9.5px;letter-spacing:.14em;text-transform:uppercase;color:#6b7280;font-weight:700;margin-bottom:6px}.mia-card .tr ul{list-style:none;font-size:12px;margin:0;padding:0}.mia-card .tr li{padding:3px 0;color:#15233b}.mia-card .tr li:before{content:"\25B8 ";color:#c98e16}.mia-tbl-w{overflow-x:auto;border:1px solid #e4e7ec;border-radius:4px;margin:14px 0}.mia-tbl{border-collapse:collapse;width:100%;font-size:12.5px;min-width:600px}.mia-tbl th,.mia-tbl td{padding:8px 12px;text-align:right;border-bottom:1px solid #eef1f5;font-variant-numeric:tabular-nums}.mia-tbl th{background:#1a3560;color:#fff;font-weight:600;font-size:11px}.mia-tbl th:first-child,.mia-tbl td:first-child{text-align:left}.mia-tbl td.na{color:#c8cdd5}</style>
<p class="mia-lede">Four numbers frame May. The index rose. Oil round-tripped. Gold fell. The five-year yield finished lower than it started. Each was unremarkable alone. Held together across seventeen trading sessions, they describe a Canadian market that migrated its entire risk thesis from one sector to another, in plain sight, while the headlines were still about a war, and then learned on the last day of the month that the economy had been in recession the whole time.</p>
<h2 id="glance" data-toc="The Month at a Glance" data-toc-n="01"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 01</span>The Month at a Glance</h2>
<div class="mia-grid"><div class="mia-stat u"><div class="v">34,518</div><div class="l">TSX close, May 29</div><div class="c p">+1.4% MTD, record 34,575</div></div><div class="mia-stat d"><div class="v"><small>US$</small>87.20</div><div class="l">WTI crude, May 29</div><div class="c n">-16.2% from May 19 peak</div></div><div class="mia-stat d"><div class="v"><small>US$</small>4,543</div><div class="l">Gold spot, May 29</div><div class="c n">-5% off early-May highs</div></div><div class="mia-stat g"><div class="v">-0.87</div><div class="l">TSX-to-oil corr, 2nd half</div><div class="c f">inverted from -0.08</div></div><div class="mia-stat "><div class="v">3.11<small>%</small></div><div class="l">GoC 5-year yield</div><div class="c n">-20 bps from May 20 peak</div></div><div class="mia-stat "><div class="v">2.25<small>%</small></div><div class="l">Bank of Canada rate</div><div class="c f">held; June decision ahead</div></div><div class="mia-stat d"><div class="v">-0.1<small>%</small></div><div class="l">Q1 GDP, annualised</div><div class="c n">first recession since 2020</div></div><div class="mia-stat "><div class="v">2.8<small>%</small></div><div class="l">Canada CPI, April</div><div class="c f">benign; bond market ignored it</div></div></div>
<p>The dashboard reads as eight independent facts. The rest of this report is the argument that they are one fact, observed from eight angles: the index relocated its sensitivity from the oil price to the rate path, and by month-end the rate path was being driven by a recession nobody had confirmed until the close.</p>
<h2 id="arc" data-toc="The Arc of the Month" data-toc-n="02"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 02</span>The Arc of the Month</h2>
<p>May opened with the market still trading the war. The Strait of Hormuz had been disrupted since early March, Brent sat above US$100, and the TSX behaved like a leveraged claim on the oil price: energy names carried the index, financials lagged, and every Iran headline moved the tape.</p>
<p>It did not end there. By the third week, crude had reversed its entire war premium, the energy trade had drained, and the index was making record highs on the strength of the sectors that benefit when oil and yields fall. The chart below traces that handover. The shaded band marks the stretch where the index pulled away from crude and never looked back.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">S&amp;P/TSX COMPOSITE</span><span style="font-size:20px;font-weight:700;color:#111;">34,518</span><span style="font-size:13px;color:#2e7d32;">&#9650; +1.4% MTD</span><span style="font-size:11px;color:#888;margin-left:auto;">Daily close &nbsp;|&nbsp; May 7-29</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function idx100(a){var b=null,o=[];for(var i=0;i<a.length;i++){if(a[i]!=null){if(b==null)b=a[i];o.push(a[i]/b*100);}else o.push(null);}return o;}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 if(C.indexed)C.series.forEach(function(s){s.data=idx100(s.data);});
 var svg=el("svg",{viewBox:"0 0 "+W+" "+H,preserveAspectRatio:"xMidYMid meet"});
 var LD=C.leftDom||dom(C.series,"left",C.pad),RD=(C.series.some(function(s){return s.axis=="right";}))?(C.rightDom||dom(C.series,"right",C.pad)):null;
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 function yR(v){return m.t+PH-PH*((v-RD[0])/(RD[1]-RD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 if(RD)for(g=0;g<=ticks;g++){var rv=RD[0]+(RD[1]-RD[0])*g/ticks;svg.appendChild(tx("text",{x:m.l+PW+5,y:yR(rv)+3,"text-anchor":"start","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(rv,C.rightType)));}
 for(var i=0;i<n;i++){if(i%2!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),(s.axis=="right"?yR(s.data[i]):yL(s.data[i]))]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}});
 if(C.pill){var s=C.series[C.pill.si],li=-1;for(var i=0;i<s.data.length;i++)if(s.data[i]!=null)li=i;var lx=xS(li),ly=(s.axis=="right"?yR(s.data[li]):yL(s.data[li])),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=document.currentScript?document.currentScript.parentNode:null;if(par)par.appendChild(svg);
}

draw({dates:["May 7", "May 8", "May 11", "May 12", "May 13", "May 14", "May 15", "May 19", "May 20", "May 21", "May 22", "May 25", "May 26", "May 27", "May 28", "May 29"],leftType:''k'',ticks:4,band:[7,13],bandColor:''#2e7d32'',bandLabel:''DECOUPLING FROM CRUDE'',events:[{i:3,t:["Ceasefire on","life support"]},{i:5,t:["Trump-Xi Hormuz","agreement"]},{i:6,t:["Gold sell-off /","Warsh signal"]},{i:9,t:["Khamenei","edict"]},{i:12,t:["Bank earnings","week"]},{i:15,t:["Recession","confirmed"]}],series:[{data:[null,34028,34078,34139,34291,34129,33833,33833,34168,34161,34410,34471,34503,34554,34412,34518],color:''#1a3560'',width:2.4,label:''TSX''}],pill:{si:0,text:''34,518'',color:''#1a3560'',w:52}});})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: TMX Group daily close &nbsp;|&nbsp; hdq.ca</div></div></div><p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">The TSX bottomed at 33,833 around the May long weekend, then climbed without a meaningful pullback to a record 34,575 intraday on May 22 even as crude rolled over. Flags mark the months defining geopolitical and data events.</p>
<p>The remainder of this report isolates the five patterns inside that arc. Each is a relationship that no single session would have shown and that, carried forward, changes how the index behaves.</p>
<h2 id="p1" data-toc="The Index That Stopped Tracking Oil" data-toc-n="P1" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern One</span>The Index That Stopped Tracking Oil</h2>
<p class="mia-lede">Across seventeen sessions the TSXs relationship to crude inverted. In the first half of May the two were effectively unrelated, at a correlation of minus 0.08. In the second half they moved in firm opposition, at minus 0.87. As oil fell, the index rose, and the tighter that inverse grip became, the higher the TSX went.</p>
<p>This is not noise. A correlation of minus 0.87 over a dozen sessions is a market that has chosen a side. Early in the month, elevated oil was the bull case: the war premium was lifting energy and that was the indexs engine. By late May the same elevated oil had become the bear case the market wanted gone, because falling crude meant falling inflation pressure, which meant a clearer path to rate relief, which lifted the financials and rate-sensitive names that make up the larger share of the index.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">TSX vs WTI CRUDE</span><span style="font-size:20px;font-weight:700;color:#111;">-0.87</span><span style="font-size:13px;color:#8a3030;">2nd-half correlation</span><span style="font-size:11px;color:#888;margin-left:auto;">from -0.08 in early May</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function idx100(a){var b=null,o=[];for(var i=0;i<a.length;i++){if(a[i]!=null){if(b==null)b=a[i];o.push(a[i]/b*100);}else o.push(null);}return o;}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 if(C.indexed)C.series.forEach(function(s){s.data=idx100(s.data);});
 var svg=el("svg",{viewBox:"0 0 "+W+" "+H,preserveAspectRatio:"xMidYMid meet"});
 var LD=C.leftDom||dom(C.series,"left",C.pad),RD=(C.series.some(function(s){return s.axis=="right";}))?(C.rightDom||dom(C.series,"right",C.pad)):null;
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 function yR(v){return m.t+PH-PH*((v-RD[0])/(RD[1]-RD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 if(RD)for(g=0;g<=ticks;g++){var rv=RD[0]+(RD[1]-RD[0])*g/ticks;svg.appendChild(tx("text",{x:m.l+PW+5,y:yR(rv)+3,"text-anchor":"start","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(rv,C.rightType)));}
 for(var i=0;i<n;i++){if(i%2!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),(s.axis=="right"?yR(s.data[i]):yL(s.data[i]))]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}});
 if(C.pill){var s=C.series[C.pill.si],li=-1;for(var i=0;i<s.data.length;i++)if(s.data[i]!=null)li=i;var lx=xS(li),ly=(s.axis=="right"?yR(s.data[li]):yL(s.data[li])),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=document.currentScript?document.currentScript.parentNode:null;if(par)par.appendChild(svg);
}

draw({dates:["May 7", "May 8", "May 11", "May 12", "May 13", "May 14", "May 15", "May 19", "May 20", "May 21", "May 22", "May 25", "May 26", "May 27", "May 28", "May 29"],leftType:''k'',rightType:''$'',ticks:4,band:[7,13],bandColor:''#8a3030'',bandOp:0.06,bandLabel:''OIL DOWN, TSX UP'',series:[{data:[null,34028,34078,34139,34291,34129,33833,33833,34168,34161,34410,34471,34503,34554,34412,34518],color:''#1a3560'',width:2.4,label:''TSX (L)''},{data:[null,null,97.55,null,102.18,100.0,103.5,104.0,99.5,97.1,null,91.0,94.16,90.96,89.27,87.2],color:''#4a5568'',width:2,axis:''right'',label:''WTI (R)''}],pill:{si:0,text:''34,518'',color:''#1a3560'',w:52},annot:[{x:360,y:255,t:''correlation -0.87'',size:9,weight:700,fill:''#8a3030'',anchor:''middle''}]});})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: TMX Group, NYMEX &nbsp;|&nbsp; hdq.ca</div></div></div><p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">TSX Composite (navy, left axis) against WTI crude (slate, right axis). The series converge early and diverge sharply after May 19, the visual signature of a market rotating out of the energy trade.</p>
<div class="mia-pull">The TSX entered May as an oil index and left it as a rate-cut index. The rotation took seventeen sessions and was never announced.</div>
<p><strong>Why it matters going forward.</strong> An advisor still modelling the TSX as a commodity-levered index is working from a relationship the market has already abandoned. The indexs marginal driver in late May was the front-end rate path, not the oil price. A portfolio built for the early-May regime, overweight energy as the TSXs growth engine, was positioned against the very rotation that drove the record highs.</p>
<h2 id="p2" data-toc="The Deflating War Premium" data-toc-n="P2" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Two</span>The Deflating War Premium</h2>
<p class="mia-lede">Crude began May near US$100, spiked to US$111 on the worst of the Hormuz headlines, then surrendered the entire premium to close the month under US$96 on Brent and at US$87 on WTI. The war did not end. The market simply stopped paying for it.</p>
<p>The arc of the oil price is the arc of a fading reflex. Early escalation headlines produced sharp spikes. Later ones produced less. By the time a false report of an Iran deal circulated on May 28, the tape moved only modestly and reversed within the session. Each successive shock had a shorter half-life than the one before it, because the market had repriced the standing disruption as the baseline rather than the emergency.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">BRENT &amp; WTI CRUDE</span><span style="font-size:20px;font-weight:700;color:#111;">$96.28</span><span style="font-size:13px;color:#8a3030;">&#9660; premium fully unwound</span><span style="font-size:11px;color:#888;margin-left:auto;">US$/bbl &nbsp;|&nbsp; May 7-29</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function idx100(a){var b=null,o=[];for(var i=0;i<a.length;i++){if(a[i]!=null){if(b==null)b=a[i];o.push(a[i]/b*100);}else o.push(null);}return o;}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 if(C.indexed)C.series.forEach(function(s){s.data=idx100(s.data);});
 var svg=el("svg",{viewBox:"0 0 "+W+" "+H,preserveAspectRatio:"xMidYMid meet"});
 var LD=C.leftDom||dom(C.series,"left",C.pad),RD=(C.series.some(function(s){return s.axis=="right";}))?(C.rightDom||dom(C.series,"right",C.pad)):null;
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 function yR(v){return m.t+PH-PH*((v-RD[0])/(RD[1]-RD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 if(RD)for(g=0;g<=ticks;g++){var rv=RD[0]+(RD[1]-RD[0])*g/ticks;svg.appendChild(tx("text",{x:m.l+PW+5,y:yR(rv)+3,"text-anchor":"start","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(rv,C.rightType)));}
 for(var i=0;i<n;i++){if(i%2!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),(s.axis=="right"?yR(s.data[i]):yL(s.data[i]))]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}});
 if(C.pill){var s=C.series[C.pill.si],li=-1;for(var i=0;i<s.data.length;i++)if(s.data[i]!=null)li=i;var lx=xS(li),ly=(s.axis=="right"?yR(s.data[li]):yL(s.data[li])),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=document.currentScript?document.currentScript.parentNode:null;if(par)par.appendChild(svg);
}

draw({dates:["May 7", "May 8", "May 11", "May 12", "May 13", "May 14", "May 15", "May 19", "May 20", "May 21", "May 22", "May 25", "May 26", "May 27", "May 28", "May 29"],leftType:''$'',ticks:5,events:[{i:3,t:["Ceasefire on","life support"]},{i:5,t:["Trump-Xi Hormuz","agreement"]},{i:6,t:["Gold sell-off /","Warsh signal"]},{i:9,t:["Khamenei","edict"]},{i:12,t:["Bank earnings","week"]},{i:15,t:["Recession","confirmed"]}],series:[{data:[100.06,100.54,101.0,94.0,107.0,null,107.0,109.0,111.0,null,104.52,null,98.11,98.26,96.28,null],color:''#4a5568'',width:2.2,label:''Brent''},{data:[null,null,97.55,null,102.18,100.0,103.5,104.0,99.5,97.1,null,91.0,94.16,90.96,89.27,87.2],color:''#9ca3af'',width:2,label:''WTI''}],pill:{si:1,text:''$87.20'',color:''#9ca3af'',w:50}});})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: ICE, NYMEX settlement &nbsp;|&nbsp; hdq.ca</div></div></div><p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">Brent (slate) and WTI (light) crude through May, with the months headlines flagged. The premium built into the May 19-20 peak fully unwound over the following seven sessions despite no resolution in the Strait.</p>
<p><strong>Why it matters going forward.</strong> The desensitisation is the signal. A market that no longer rewards escalation headlines has a smaller cushion if a genuine supply break arrives, because the premium that would normally absorb it has already bled out. The same fading reflex that powered the equity rally is what leaves crude exposed to a real shock it is no longer pricing.</p>
<h2 id="p3" data-toc="The Safe Haven That Wasnt" data-toc-n="P3" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Three</span>The Safe Haven That Wasnt</h2>
<p class="mia-lede">Through a month with an open conflict and a closed shipping strait, gold fell five percent. The asset that is supposed to rise on exactly this kind of fear declined steadily from above US$4,700 to roughly US$4,490 before a small month-end bounce, even on days oil was surging.</p>
<p>The explanation is the tell of the whole month. Gold and oil are both called safe havens, but they answer to different masters. Oil held its bid on the physical supply risk. Gold was governed by real yields, and real yields were rising on a hawkish signal out of the US rate debate that pushed the US 10-year toward a one-year high. When the carrying cost of a non-yielding asset rises, gold falls regardless of the geopolitical backdrop. The two havens diverged because only one of them was actually trading the war.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">GOLD vs BRENT &mdash; INDEXED TO 100</span><span style="font-size:20px;font-weight:700;color:#111;">-5.0%</span><span style="font-size:13px;color:#8a3030;">gold, through a shooting war</span><span style="font-size:11px;color:#888;margin-left:auto;">May 8 = 100</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function idx100(a){var b=null,o=[];for(var i=0;i<a.length;i++){if(a[i]!=null){if(b==null)b=a[i];o.push(a[i]/b*100);}else o.push(null);}return o;}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 if(C.indexed)C.series.forEach(function(s){s.data=idx100(s.data);});
 var svg=el("svg",{viewBox:"0 0 "+W+" "+H,preserveAspectRatio:"xMidYMid meet"});
 var LD=C.leftDom||dom(C.series,"left",C.pad),RD=(C.series.some(function(s){return s.axis=="right";}))?(C.rightDom||dom(C.series,"right",C.pad)):null;
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 function yR(v){return m.t+PH-PH*((v-RD[0])/(RD[1]-RD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 if(RD)for(g=0;g<=ticks;g++){var rv=RD[0]+(RD[1]-RD[0])*g/ticks;svg.appendChild(tx("text",{x:m.l+PW+5,y:yR(rv)+3,"text-anchor":"start","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(rv,C.rightType)));}
 for(var i=0;i<n;i++){if(i%2!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),(s.axis=="right"?yR(s.data[i]):yL(s.data[i]))]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}});
 if(C.pill){var s=C.series[C.pill.si],li=-1;for(var i=0;i<s.data.length;i++)if(s.data[i]!=null)li=i;var lx=xS(li),ly=(s.axis=="right"?yR(s.data[li]):yL(s.data[li])),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=document.currentScript?document.currentScript.parentNode:null;if(par)par.appendChild(svg);
}

draw({dates:["May 7", "May 8", "May 11", "May 12", "May 13", "May 14", "May 15", "May 19", "May 20", "May 21", "May 22", "May 25", "May 26", "May 27", "May 28", "May 29"],leftType:''idx'',ticks:4,indexed:true,series:[{data:[100.06,100.54,101.0,94.0,107.0,null,107.0,109.0,111.0,null,104.52,null,98.11,98.26,96.28,null],color:''#4a5568'',width:2.2,label:''Brent''},{data:[null,4725,null,4678,null,null,4555,4531,4487,4514,4524,null,null,null,null,4543],color:''#c98e16'',width:2.4,label:''Gold''}],annot:[{x:520,y:88,t:''oil whipsaws, holds bid'',size:8,weight:700,fill:''#4a5568'',anchor:''end''},{x:430,y:232,t:''gold fades on real yields'',size:8,weight:700,fill:''#c98e16'',anchor:''end''}]});})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: LBMA, ICE. Indexed to May 8 open &nbsp;|&nbsp; hdq.ca</div></div></div><p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">Gold and Brent crude, each indexed to 100 at the May 8 open. Oil whipsaws on the headlines while gold drifts steadily lower, isolating real yields rather than geopolitics as the dominant force on the gold price.</p>
<div class="mia-pull">When the two safe havens disagree, the bond market is the one telling the truth. In May, gold was reading the yield curve while oil was reading the news.</div>
<p><strong>Why it matters going forward.</strong> Golds behaviour in May is a caution against holding it as a geopolitical hedge in a rising-real-yield regime. Its drawdown was not a failure of the haven thesis; it was confirmation that, this cycle, the yield environment outranks the headline environment. A hedge that moves on a variable the holder is not watching is not the hedge they think they own.</p>
<h2 id="p4" data-toc="Yields Tracked Oil, Not Inflation" data-toc-n="P4" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Four</span>Yields Tracked Oil, Not Inflation</h2>
<p class="mia-lede">Canadas April CPI came in at a benign 2.8%, and on the morning it landed the bond market did not move. The Government of Canada five-year yield held near 3.3% regardless. What it did respond to was crude: across the month the five-year tracked oil at a correlation of plus 0.52, and the realised inflation print barely registered.</p>
<p>The bond market was not pricing the inflation that had happened. It was pricing the inflation that elevated oil threatened to create. So long as crude stayed bid, the five-year stayed elevated; when oil broke down in the final week, the yield followed it lower, finishing the month twenty basis points below its peak. The CPI release was a footnote. The oil price was the input.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">GoC 5-YEAR YIELD vs WTI</span><span style="font-size:20px;font-weight:700;color:#111;">3.11%</span><span style="font-size:13px;color:#2e7d32;">&#9660; -20 bps from peak</span><span style="font-size:11px;color:#888;margin-left:auto;">corr to crude +0.52</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function idx100(a){var b=null,o=[];for(var i=0;i<a.length;i++){if(a[i]!=null){if(b==null)b=a[i];o.push(a[i]/b*100);}else o.push(null);}return o;}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 if(C.indexed)C.series.forEach(function(s){s.data=idx100(s.data);});
 var svg=el("svg",{viewBox:"0 0 "+W+" "+H,preserveAspectRatio:"xMidYMid meet"});
 var LD=C.leftDom||dom(C.series,"left",C.pad),RD=(C.series.some(function(s){return s.axis=="right";}))?(C.rightDom||dom(C.series,"right",C.pad)):null;
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 function yR(v){return m.t+PH-PH*((v-RD[0])/(RD[1]-RD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 if(RD)for(g=0;g<=ticks;g++){var rv=RD[0]+(RD[1]-RD[0])*g/ticks;svg.appendChild(tx("text",{x:m.l+PW+5,y:yR(rv)+3,"text-anchor":"start","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(rv,C.rightType)));}
 for(var i=0;i<n;i++){if(i%2!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),(s.axis=="right"?yR(s.data[i]):yL(s.data[i]))]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}});
 if(C.pill){var s=C.series[C.pill.si],li=-1;for(var i=0;i<s.data.length;i++)if(s.data[i]!=null)li=i;var lx=xS(li),ly=(s.axis=="right"?yR(s.data[li]):yL(s.data[li])),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=document.currentScript?document.currentScript.parentNode:null;if(par)par.appendChild(svg);
}

draw({dates:["May 7", "May 8", "May 11", "May 12", "May 13", "May 14", "May 15", "May 19", "May 20", "May 21", "May 22", "May 25", "May 26", "May 27", "May 28", "May 29"],leftType:''pct2'',rightType:''$'',ticks:4,events:[{i:7,t:[''CPI 2.8%'',''bond mkt shrugs'']}],series:[{data:[3.27,null,null,3.2,null,null,3.2,3.31,3.31,3.31,null,3.12,null,3.14,3.14,3.11],color:''#1a3560'',width:2.4,label:''GoC 5Y (L)''},{data:[null,null,97.55,null,102.18,100.0,103.5,104.0,99.5,97.1,null,91.0,94.16,90.96,89.27,87.2],color:''#4a5568'',width:2,axis:''right'',label:''WTI (R)''}],pill:{si:0,text:''3.11%'',color:''#1a3560'',w:46},annot:[{x:340,y:255,t:''yield tracks oil +0.52'',size:9,weight:700,fill:''#1a3560'',anchor:''middle''}]});})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: Bank of Canada, NYMEX &nbsp;|&nbsp; hdq.ca</div></div></div><p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">GoC 5-year yield (navy, left) against WTI crude (slate, right). The yield ignores the benign April CPI flagged mid-chart and instead falls in step with crude into month-end.</p>
<p><strong>Why it matters going forward.</strong> The five-year yield is the reference rate for Canadian fixed mortgage pricing, and a wall of renewals runs through 2026 and 2027. In May, the rate that sets those renewals was being determined in the oil market, not by domestic inflation data. For a household renewing this year, the most relevant chart was not the CPI release. It was the crude curve. That linkage holds as long as oil remains the bond markets inflation proxy, and it gives an unusually clean read: watch the front of the oil curve to anticipate the renewal rate.</p>
<h2 id="p5" data-toc="The Banks Beat, the Tape Fell" data-toc-n="P5" data-toc-sub="1"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Pattern Five</span>The Banks Beat, the Tape Fell</h2>
<p class="mia-lede">Bank earnings week closed the month with strong results. BMO reported net income up 34% year over year and beat on adjusted earnings; TD beat as well. On the sessions the banks reported, the TSX rolled over anyway.</p>
<p>The beats were real. The disappointment was structural. Financials had already rallied hard into the prints, climbing through the third week on the same rate-relief logic driving the broader rotation. By the time the earnings confirmed the thesis, the move was in the price. The market had bought the expectation and sold the fact, the oldest pattern in the book, executed cleanly on Canadas largest sector.</p>
<div class="hdq-chart"><div style="background:#ffffff;border:1px solid #d0d0d0;width:100%;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"><div style="background:#f5f5f5;border-bottom:1px solid #d0d0d0;padding:10px 14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;"><span style="font-size:13px;font-weight:700;color:#111;letter-spacing:0.02em;">TSX THROUGH BANK-EARNINGS WEEK</span><span style="font-size:20px;font-weight:700;color:#111;">+34%</span><span style="font-size:13px;color:#3a7a55;">BMO net income, yet the tape fell</span><span style="font-size:11px;color:#888;margin-left:auto;">May 20-29</span></div><div style="padding:12px 14px 8px;"><script>(function(){
var NS="http://www.w3.org/2000/svg",F="-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif";
function el(t,a){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);return e;}
function tx(t,a,s){var e=el(t,a);e.textContent=s;return e;}
function fmt(v,ty){if(ty=="k")return (v/1000).toFixed(1)+"k";if(ty=="$")return "$"+Math.round(v);if(ty=="pct2")return v.toFixed(2)+"%";if(ty=="idx")return Math.round(v);if(ty=="int")return Math.round(v).toLocaleString();return Math.round(v);}
function dom(series,axis,pad){var vv=[];series.forEach(function(s){if((s.axis||"left")==axis)s.data.forEach(function(x){if(x!=null)vv.push(x);});});if(!vv.length)return[0,1];var mn=Math.min.apply(null,vv),mx=Math.max.apply(null,vv),r=mx-mn;if(r==0)r=Math.abs(mx)*0.1||1;var p=r*(pad||0.14);return[mn-p,mx+p];}
function idx100(a){var b=null,o=[];for(var i=0;i<a.length;i++){if(a[i]!=null){if(b==null)b=a[i];o.push(a[i]/b*100);}else o.push(null);}return o;}
function draw(C){
 var W=680,H=C.H||300,m=C.m||{l:52,r:54,t:24,b:42},PW=W-m.l-m.r,PH=H-m.t-m.b,n=C.dates.length;
 if(C.indexed)C.series.forEach(function(s){s.data=idx100(s.data);});
 var svg=el("svg",{viewBox:"0 0 "+W+" "+H,preserveAspectRatio:"xMidYMid meet"});
 var LD=C.leftDom||dom(C.series,"left",C.pad),RD=(C.series.some(function(s){return s.axis=="right";}))?(C.rightDom||dom(C.series,"right",C.pad)):null;
 function xS(i){return m.l+PW*(i/(n-1));}
 function yL(v){return m.t+PH-PH*((v-LD[0])/(LD[1]-LD[0]));}
 function yR(v){return m.t+PH-PH*((v-RD[0])/(RD[1]-RD[0]));}
 var ticks=C.ticks||4,g;
 for(g=0;g<=ticks;g++){var lv=LD[0]+(LD[1]-LD[0])*g/ticks,yy=yL(lv);svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:yy,y2:yy,stroke:"#ececec","stroke-width":0.5}));svg.appendChild(tx("text",{x:m.l-6,y:yy+3,"text-anchor":"end","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(lv,C.leftType)));}
 if(RD)for(g=0;g<=ticks;g++){var rv=RD[0]+(RD[1]-RD[0])*g/ticks;svg.appendChild(tx("text",{x:m.l+PW+5,y:yR(rv)+3,"text-anchor":"start","font-family":F,"font-size":8.5,fill:"#aaa"},fmt(rv,C.rightType)));}
 for(var i=0;i<n;i++){if(i%2!=0&&i!=n-1)continue;svg.appendChild(tx("text",{x:xS(i),y:H-m.b+15,"text-anchor":"middle","font-family":F,"font-size":8,fill:"#999"},C.dates[i]));}
 svg.appendChild(el("line",{x1:m.l,x2:m.l+PW,y1:m.t+PH,y2:m.t+PH,stroke:"#d8d8d8","stroke-width":1}));
 if(C.band){var b1=xS(C.band[0]),b2=xS(C.band[1]);svg.appendChild(el("rect",{x:b1,y:m.t,width:b2-b1,height:PH,fill:C.bandColor||"#2e7d32","fill-opacity":C.bandOp||0.07}));if(C.bandLabel)svg.appendChild(tx("text",{x:(b1+b2)/2,y:m.t+12,"text-anchor":"middle","font-family":F,"font-size":7.5,"font-weight":700,fill:C.bandColor||"#2e7d32"},C.bandLabel));}
 if(C.events){var prev=-99;C.events.forEach(function(ev){var ex=xS(ev.i),crowded=(ex-prev)<58;prev=ex;svg.appendChild(el("line",{x1:ex,x2:ex,y1:m.t,y2:m.t+PH,stroke:"#1a3560","stroke-opacity":0.4,"stroke-dasharray":"2,3","stroke-width":1}));var an=ev.i>n*0.6?"end":"start",dx=an=="end"?-3:3,y0=m.t+10+(crowded?20:0);ev.t.forEach(function(L,li){svg.appendChild(tx("text",{x:ex+dx,y:y0+li*8,"text-anchor":an,"font-family":F,"font-size":7,"font-weight":700,fill:"#1a3560"},L));});});}
 C.series.forEach(function(s){var pts=[];for(var i=0;i<s.data.length;i++){if(s.data[i]!=null)pts.push([xS(i),(s.axis=="right"?yR(s.data[i]):yL(s.data[i]))]);}var d=pts.map(function(q,i){return(i?"L":"M")+q[0].toFixed(1)+" "+q[1].toFixed(1);}).join(" ");svg.appendChild(el("path",{d:d,fill:"none",stroke:s.color,"stroke-width":s.width||2,"stroke-dasharray":s.dash||"none","stroke-linejoin":"round","stroke-linecap":"round"}));if(s.label){var Lp=pts[pts.length-1];svg.appendChild(tx("text",{x:Lp[0]-4,y:Lp[1]-6,"text-anchor":"end","font-family":F,"font-size":7.5,"font-weight":700,fill:s.color},s.label));}});
 if(C.pill){var s=C.series[C.pill.si],li=-1;for(var i=0;i<s.data.length;i++)if(s.data[i]!=null)li=i;var lx=xS(li),ly=(s.axis=="right"?yR(s.data[li]):yL(s.data[li])),pw=C.pill.w||52,ph=16,px=lx-pw-6;if(px<m.l)px=lx+6;var py=ly-ph/2;if(py<m.t)py=m.t+2;if(py+ph>m.t+PH)py=m.t+PH-ph-2;svg.appendChild(el("circle",{cx:lx,cy:ly,r:3.5,fill:C.pill.color||"#4a5568"}));svg.appendChild(el("rect",{x:px,y:py,width:pw,height:ph,rx:2,fill:"#e8a825"}));svg.appendChild(tx("text",{x:px+pw/2,y:py+ph/2+3.5,"text-anchor":"middle","font-family":F,"font-size":9,"font-weight":700,fill:"#111"},C.pill.text));}
 if(C.annot)C.annot.forEach(function(a){svg.appendChild(tx("text",{x:a.x,y:a.y,"text-anchor":a.anchor||"start","font-family":F,"font-size":a.size||8,"font-weight":a.weight||400,fill:a.fill||"#444"},a.t));});
 var par=document.currentScript?document.currentScript.parentNode:null;if(par)par.appendChild(svg);
}

draw({dates:["May 7", "May 8", "May 11", "May 12", "May 13", "May 14", "May 15", "May 19", "May 20", "May 21", "May 22", "May 25", "May 26", "May 27", "May 28", "May 29"],leftType:''k'',ticks:4,events:[{i:12,t:[''BMO reports'',''+34% net income'']},{i:13,t:[''TD beats'']}],series:[{data:[null,null,null,null,null,null,null,null,34168,34161,34410,34471,34503,34554,34412,34518],color:''#1a3560'',width:2.6,label:''TSX''}],pill:{si:0,text:''34,518'',color:''#1a3560'',w:52},annot:[{x:300,y:64,t:''record 34,554 as beats land'',size:8,weight:700,fill:''#2e7d32'',anchor:''start''},{x:600,y:150,t:''sell-the-news give-back'',size:8,weight:700,fill:''#8a3030'',anchor:''end''}]});})();</script></div><div style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:10px;color:#999;padding:4px 14px 10px;font-style:italic;">Source: TMX Group, company Q2 filings &nbsp;|&nbsp; hdq.ca</div></div></div><p style="font-size:11px;color:#666;font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;margin-top:6px;">The TSX across the bank-earnings window. The index pushed to its 34,554 high as the beats landed, then gave back ground on the reporting sessions despite results that confirmed the bull case.</p>
<p><strong>Why it matters going forward.</strong> In the late-May regime the financials had become the indexs lead horse, which means they also carry its positioning risk. A sector that leads on the way up concentrates the crowd, and a confirmed-but-priced catalyst is precisely when crowded trades wobble. The signal for the months ahead is not the earnings quality. It is how much of the good news is already in the tape before the news arrives.</p>
<h2 id="forward" data-toc="What the Patterns Imply" data-toc-n="03"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 03</span>What the Patterns Imply</h2>
<p>The five patterns converge on a single structure. The Canadian market has relocated its sensitivity from the oil price to the rate path, and the oil price has become the bond markets proxy for where that rate path goes. The May 29 recession confirmation sharpens the point: a contracting economy makes the case for rate relief on its own, independent of oil, which means the rotation that defined the month now has two engines behind it rather than one.</p>
<p>That structure produces three forward paths. Each is defined by where crude settles, what it does to the five-year yield, and how the Bank of Canada reads a recession against a still-elevated war premium. The trigger levels below are the markers that would confirm each path.</p>
<div class="mia-scen"><div class="mia-card base"><div class="t"><div class="nm">Base case</div><div class="pr">most probable</div></div><div class="bd"><p>Crude stabilises in the high US$80s. The five-year holds near 3.1%, premium already given back. The recession tilts the Bank dovish, and the rotation into rate-sensitive sectors persists but cools as the easy repricing is done.</p><p>The index grinds higher rather than surges, leadership staying in financials.</p></div><div class="tr"><div class="lb">Confirms if</div><ul><li>WTI holds US$85-92</li><li>GoC 5Y in 3.05-3.20%</li><li>BoC holds, dovish tone</li></ul></div></div><div class="mia-card bull"><div class="t"><div class="nm">Rate-relief upside</div><div class="pr">constructive</div></div><div class="bd"><p>Crude drifts toward the low US$80s and the recession data builds. The five-year breaks below 3.0%, easing the renewal-wall math and reinforcing the financials bid.</p><p>The pattern-four linkage works for the index: cheaper oil pulls the renewal rate down directly and the May rotation extends.</p></div><div class="tr"><div class="lb">Confirms if</div><ul><li>WTI below US$83</li><li>GoC 5Y under 3.00%</li><li>BoC signals a cut</li></ul></div></div><div class="mia-card bear"><div class="t"><div class="nm">Shock repricing</div><div class="pr">tail risk</div></div><div class="bd"><p>A genuine Hormuz supply break arrives into a market that stopped pricing one. Crude gaps back through US$110, and because the premium was fully drained, the move is violent.</p><p>The five-year reverses higher, the Bank is caught between recession and imported inflation, and the desensitised tape has no cushion.</p></div><div class="tr"><div class="lb">Confirms if</div><ul><li>WTI gaps above US$100</li><li>GoC 5Y back above 3.40%</li><li>BoC forced to hold hawkish</li></ul></div></div></div>
<p>The asymmetry is worth stating plainly. Patterns one through four all lean the same way in the base and upside paths, which is why the month felt so one-directional, and the recession reinforces them. The risk is concentrated entirely in the tail: the same desensitisation that powered the rally is what removes the shock absorber if the supply break the market stopped fearing actually happens.</p>
<h2 id="appendix" data-toc="Data Appendix" data-toc-n="04"><span class="ix" style="font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;font-size:13px;font-weight:700;color:#c98e16;letter-spacing:.1em;display:block;margin-bottom:8px;text-transform:uppercase;">Section 04</span>Data Appendix</h2>
<p>The daily closing series underlying every chart and figure in this report. Blank cells indicate a session for which a clean close was not captured for that instrument; May 18 was a market holiday.</p>
<div class="mia-tbl-w"><table class="mia-tbl"><thead><tr><th>Session</th><th>TSX</th><th>WTI US$</th><th>Brent US$</th><th>Gold US$</th><th>GoC 5Y %</th><th>CAD/USD</th></tr></thead><tbody><tr><td>May 7</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td>100.06</td><td class="na">&mdash;</td><td>3.27</td><td class="na">&mdash;</td></tr><tr><td>May 8</td><td>34,028</td><td class="na">&mdash;</td><td>100.54</td><td>4,725</td><td class="na">&mdash;</td><td>0.7310</td></tr><tr><td>May 11</td><td>34,078</td><td>97.55</td><td>101.00</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td class="na">&mdash;</td></tr><tr><td>May 12</td><td>34,139</td><td class="na">&mdash;</td><td>94.00</td><td>4,678</td><td>3.20</td><td class="na">&mdash;</td></tr><tr><td>May 13</td><td>34,291</td><td>102.18</td><td>107.00</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td>0.7293</td></tr><tr><td>May 14</td><td>34,129</td><td>100.00</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td>0.7298</td></tr><tr><td>May 15</td><td>33,833</td><td>103.50</td><td>107.00</td><td>4,555</td><td>3.20</td><td class="na">&mdash;</td></tr><tr><td>May 19</td><td>33,833</td><td>104.00</td><td>109.00</td><td>4,531</td><td>3.31</td><td class="na">&mdash;</td></tr><tr><td>May 20</td><td>34,168</td><td>99.50</td><td>111.00</td><td>4,487</td><td>3.31</td><td>0.7269</td></tr><tr><td>May 21</td><td>34,161</td><td>97.10</td><td class="na">&mdash;</td><td>4,514</td><td>3.31</td><td>0.7312</td></tr><tr><td>May 22</td><td>34,410</td><td class="na">&mdash;</td><td>104.52</td><td>4,524</td><td class="na">&mdash;</td><td>0.7280</td></tr><tr><td>May 25</td><td>34,471</td><td>91.00</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td>3.12</td><td>0.7236</td></tr><tr><td>May 26</td><td>34,503</td><td>94.16</td><td>98.11</td><td class="na">&mdash;</td><td class="na">&mdash;</td><td>0.7236</td></tr><tr><td>May 27</td><td>34,554</td><td>90.96</td><td>98.26</td><td class="na">&mdash;</td><td>3.14</td><td>0.7237</td></tr><tr><td>May 28</td><td>34,412</td><td>89.27</td><td>96.28</td><td class="na">&mdash;</td><td>3.14</td><td class="na">&mdash;</td></tr><tr><td>May 29</td><td>34,518</td><td>87.20</td><td class="na">&mdash;</td><td>4,543</td><td>3.11</td><td>0.7251</td></tr></tbody></table></div>',
'',
'',
'[{"value":"+1.4%","label":"TSX, May (record high)"},{"value":"-16.2%","label":"WTI crude from peak"},{"value":"-0.87","label":"TSX-oil correlation, 2nd half"},{"value":"-0.1%","label":"Q1 GDP: technical recession"}]',
'month-may-2026.jpg',
'May 2026 surveyed as a whole: a month that opened trading a war and closed trading a recession, with the index higher at both ends. Photo: iStock.',
12,
'2026-05-29T17:00:00',
'entity:tsx,entity:wti,entity:brent,entity:goc-5y,entity:gold,entity:boc,theme:hormuz-disruption,theme:cdn-energy-rerating,theme:boc-rate-path,theme:canadian-recession-risk,theme:gold-safe-haven,stance:framing-shift',
0,
'TMX Group daily close data; ICE Brent and NYMEX WTI settlement; LBMA gold fixings; Bank of Canada benchmark bond yields; Statistics Canada GDP and CPI releases; company Q2 2026 filings (BMO, TD). All figures reflect closing levels captured across the seventeen trading sessions of May 2026.'
);
